/**
 * Writes web/js/env.js from repo .env and process.env (VITE_* only).
 * Invoked by `npm run build` and the Trunk pre_build hook.
 */

const { readFileSync, writeFileSync, existsSync } = require("node:fs");
const { resolve, dirname } = require("node:path");

const webDir = resolve(__dirname, "..");
const repoRoot = resolve(webDir, "..");
const envFile = resolve(repoRoot, ".env");
const outFile = resolve(webDir, "js/env.js");

const KEYS = ["VITE_VAPI_PUBLIC_KEY", "VITE_INSFORGE_URL"];

/** @type {Record<string, string>} */
const values = Object.fromEntries(KEYS.map((key) => [key, ""]));

if (existsSync(envFile)) {
  const content = readFileSync(envFile, "utf8");
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    if (!KEYS.includes(key)) continue;
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
}

for (const key of KEYS) {
  if (process.env[key]) {
    values[key] = process.env[key];
  }
}

const body = `// Generated by web/scripts/write-env.js — do not edit by hand.
window.__ENV__ = Object.assign(window.__ENV__ || {}, ${JSON.stringify(values, null, 2)});
`;

writeFileSync(outFile, body, "utf8");
console.log(`[write-env] wrote ${outFile}`);
